byu_news_consumer.settings:
  type: config_object
  label: 'BYU News Consumer Config Settings'
  mapping:
    tag_ids:
      type: string
      label: 'Tag IDs'
    last_full_sync:
      type: string
      label: 'Last Full Sync'
    last_sync:
      type: string
      labe: 'Last Sync'